version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api
    networks:
      - fanfiq-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fanfiq
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - fanfiq-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fanfiq
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fanfiq-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - fanfiq-network

  # Parsers (example for one parser)
  parser-ao3:
    build:
      context: ./parsers/ao3
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fanfiq
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - fanfiq-network

networks:
  fanfiq-network:
    driver: bridge

volumes:
  postgres_data:
