[build]
builder = "nixpacks"

[[services]]
name = "api"
rootDirectory = "backend/api"
startCommand = "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "frontend"
rootDirectory = "frontend"
startCommand = "npm run start"

[[services]]
name = "worker"
rootDirectory = "backend"
startCommand = "celery -A workers.celery_app:app worker -Q crawl,normalize -l info"
