[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# API Service
[[services]]
name = "api"
rootDirectory = "backend/api"

[services.deploy]
startCommand = "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30

[[services.envVars]]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"

# Frontend Service
[[services]]
name = "frontend"
rootDirectory = "frontend"

[services.deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30

[[services.envVars]]
NEXT_PUBLIC_API_URL = "https://${{api.RAILWAY_PUBLIC_DOMAIN}}"

# Worker Service
[[services]]
name = "worker"
rootDirectory = "backend"

[services.deploy]
startCommand = "celery -A workers.celery_app:app worker -Q crawl,normalize -l info"

[[services.envVars]]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
CELERY_BROKER_URL = "${{Redis.REDIS_URL}}"
