name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  backend-ci:
    name: Backend API CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/api/requirements.txt

      - name: Validate Alembic env imports
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module('backend.api.alembic.env')
          print('alembic env import ok')
          PY

      - name: Build API Docker image
        run: |
          docker build -f backend/api/Dockerfile -t fanfiq-api:ci .
